"""replace uuid with universaluuid

Revision ID: 43a19d32268c
Revises: 280b88d7ce6a
Create Date: 2025-06-01 18:05:57.519764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a19d32268c'
down_revision = '280b88d7ce6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
